# Generated by Django 4.0 on 2021-12-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('uid', models.IntegerField()),
                ('prop_good', models.FloatField(default=None)),
                ('prop_bad', models.FloatField(default=None)),
            ],
        ),
    ]
